version: '3.1'

services:
  web:
    image: node
    command: npm run start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_USER: root
      DB_PASS: root
      DB_NAME: cloudDB
      DB_HOST: db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudDB